package io.romain.passport.model;

import android.net.Uri;
import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import com.squareup.okhttp.RequestBody;
import com.squareup.okhttp.Response;

import java.io.IOException;

import javax.security.auth.login.LoginException;

import retrofit.Call;
import retrofit.http.Body;
import retrofit.http.GET;
import retrofit.http.Multipart;
import retrofit.http.POST;
import retrofit.http.Part;
import retrofit.http.Path;
import retrofit.http.Query;

// This is not a persistable model since it will be saved onto the account manager;
public class User implements Parcelable {
	// api endpoint
	private static final String MODULE = "/users";

	// endpoints
	private static final String POST_FILE = "/files/{filename}";

	private static final String POST_REGISTER = MODULE + "/register";
	private static final String GET_LOGIN = MODULE + "/login";
	private static final String PUT_GCM = MODULE + "/gcm/{gcm_token}";

	@Expose
	@SerializedName("_id")
	public String id;

	@Expose
	@SerializedName("name")
	public String name;

	@Expose
	@SerializedName("email")
	public String email;

	@Expose
	@SerializedName("token")
	public String token;

	@Expose
	@SerializedName("password")
	public String password;

	@Expose
	@SerializedName("picture")
	public Uri picture;

	public User(String email, String name, String password) {
		this.email = email;
		this.name = name;
		this.password = password;
	}

	public interface UserService {

		@POST(POST_REGISTER)
		Call<User> register(@Body User user);

		@GET(GET_LOGIN)
		Call<User> login(@Query("username") String email, @Query("password") String password) throws IOException;

		@Multipart
		@POST(POST_FILE)
		Call<Response> upload(@Part("file\"; filename=\"profile.png\" ") RequestBody file,
		                      @Part("description") String description) throws IOException;

		@POST(PUT_GCM)
		Call<User> registerGcm(@Path("gcm_token") String token) throws LoginException;
	}

	// ############### AUTOGENERATED STUFFS


	@Override
	public String toString() {
		return "User{" +
				"name='" + name + '\'' +
				", email='" + email + '\'' +
				'}';
	}

	@Override
	public int describeContents() {
		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeString(this.id);
		dest.writeString(this.name);
		dest.writeString(this.email);
		dest.writeString(this.token);
		dest.writeString(this.password);
		dest.writeParcelable(this.picture, 0);
	}

	protected User(Parcel in) {
		this.id = in.readString();
		this.name = in.readString();
		this.email = in.readString();
		this.token = in.readString();
		this.password = in.readString();
		this.picture = in.readParcelable(Uri.class.getClassLoader());
	}

	public static final Creator<User> CREATOR = new Creator<User>() {
		public User createFromParcel(Parcel source) {
			return new User(source);
		}

		public User[] newArray(int size) {
			return new User[size];
		}
	};
}
